### ISSUE TITLE
Etkinlik slug'ı otomatik yaratılmalı

### ISSUE THREAD

**Issue by berkerpeksag** [emre/lkd-courses#17]

**Comment by emre** [comment]
unicode_tr içindeki slugify'ı kullanalım. built-in slug, küçük ı karakteri için sıkıntı yaşıyor.

**Comment by berkerpeksag** [comment]
hiç slug fonksiyonuyla uğraşmadan prepopulated_fields ile yapmayı planlıyordum ben.

**Comment by berkerpeksag** [comment]
Şu anki kurslar gibi: https://github.com/emre/lkd-courses/blob/master/lkdcourses/courses/admin.py#L7
