### ISSUE TITLE
Sik Sorulanlar Sayfasi

### ISSUE THREAD

**Issue by mofm** [emre/lkd-courses#20]
Ozellikle, basvuruda sitenin her tarafinda basvuranlarin gozune batan bir SSS sayfasi hazirlanmasi.

**Comment by berkerpeksag** [comment]
SSS sayfası genel mi her etkinliğe göre değişen bir şey mi?

**Comment by mofm** [comment]
Etkinlige ozel olmali.

**Comment by emre** [comment]
Event modelinde FAQ adında bir text alan var.
https://github.com/emre/lkd-courses/blob/master/lkdcourses/courses/models.py#L63

**Comment by berkerpeksag** [comment]
@mofm kodu okuyup issue aç....
