### ISSUE TITLE
UserProfile'ı custom User model'i içine al

### ISSUE THREAD

**Issue by berkerpeksag** [emre/lkd-courses#22]
Bu direkt olarak #1'e bağımlı değil ama orada zaten yapacağımız değişikliklere bu issue'da da ihtiyacımız olacak.

**Comment by emre** [comment]
bende.

**Comment by emre** [comment]
https://github.com/emre/lkd-courses/commit/e4e4bb7ac94206e3ffe0a0dc238ece532c5586b0
