### ISSUE TITLE
Kullanıcı profiline kara ve gri liste seçenekleri ekle

### ISSUE THREAD

**Issue by berkerpeksag** [emre/lkd-courses#6]
Sadece yöneticiler tarafından görülecek ve değiştirilebilecek.

**Comment by mofm** [comment]
Neden kara ya da gri listeye girdigi konusunda bir aciklama/yorum koyabilmeliyiz.

**Comment by berkerpeksag** [comment]
AdministrativeNote modeli dediğin işe yarıyor galiba.

**Comment by emre** [comment]
AdministrativeNote modeline note_type =  ("gray", "black") ekleyebiliriz.

**Comment by emre** [comment]
https://github.com/emre/lkd-courses/commit/2383bf1eb6ca525dbba42bf04432036726bdefde
